// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package ordersrepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrdersEvent struct {
	OrderID     int64
	OrderStatus int32
	CreatedAt   pgtype.Timestamp
	SendStatus  int32
	SendAt      pgtype.Timestamp
}

type OrdersInfo struct {
	OrderID int64
	Status  int32
	UserID  int64
}

type OrdersItem struct {
	OrderID int64
	ItemID  int64
	Count   int32
}
